const ApiTypes = {
  RASSEN: "/api/ras.page",
  REGISTERAPI: "/api/auth/register.page",
  LOGINAPI: "/api/auth/login.page",
  RESERVATIEAPI: "/api/boekings.page",
  KLANT_HONDEN: "/api/klant/honden.page",
  LOGOUT: "/api/auth/logout.page",
  GET_FUTURE_INSCHRIJVINGS: "/api/inschrijvingen.page",
  POST_INSCHRIJVING: "/api/inschrijvingen.page",
  TRANSFER: "/api/transfer.page",
  CONTACTAPI: "/api/contact.page",
  CONTENTINTRO: "/api/content/62fa1f25bacc03711136ad59.page",
  CONTENTDIENSTEN: "/api/content/633862b5fbcc3a3006dcda52.page",
  CONTENTPRIVETRAINING: "/api/trainingen/62fa1f25bacc03711136ad5f.page",
  ADMIN_KLANTEN_OVERVIEW: "/api/admin/klanten.page",
  ADMIN_KLANT_DETAIL: "/api/admin/klanten/index.page",
  ADMIN_INSCHRIJVINGEN_OVERVIEW: "/api/admin/inschrijvingen.page",
  ADMIN_INSCHRIJVING_DETAIL: "/api/admin/inschrijvingen/index.page",
  ADMIN_HONDEN_OVERVIEW: "/api/admin/honden.page",
  ADMIN_HOND_DETAIL: "/api/admin/honden/index.page",
  ADMIN_RASSEN_OVERIEW: "/api/admin/rassen.page",
  ADMIN_RAS_DETAIL: "/api/admin/ras/index.page",
};

export const {
  RASSEN,
  REGISTERAPI,
  LOGINAPI,
  RESERVATIEAPI,
  KLANT_HONDEN,
  LOGOUT,
  GET_FUTURE_INSCHRIJVINGS,
  POST_INSCHRIJVING,
  TRANSFER,
  CONTACTAPI,
  CONTENTPRIVETRAINING,
  CONTENTINTRO,
  CONTENTDIENSTEN,
  ADMIN_KLANTEN_OVERVIEW,
  ADMIN_KLANT_DETAIL,
  ADMIN_INSCHRIJVINGEN_OVERVIEW,
  ADMIN_INSCHRIJVING_DETAIL,
  ADMIN_HONDEN_OVERVIEW,
  ADMIN_HOND_DETAIL,
  ADMIN_RASSEN_OVERIEW,
  ADMIN_RAS_DETAIL,
} = ApiTypes;
