const ApiTypes = {
  RASSEN: '/api/ras',
  REGISTERAPI: '/api/auth/register',
  LOGINAPI: '/api/auth/login',
  RESERVATIEAPI: '/api/boekings',
  KLANT_HONDEN: '/api/klant/honden',
  LOGOUT: '/api/auth/logout',
  GET_FUTURE_INSCHRIJVINGS: '/api/inschrijvingen',
  POST_INSCHRIJVING: '/api/inschrijvingen',
  TRANSFER: '/api/transfer',
  CONTACTAPI: '/api/contact',
  CONTENTINTRO: '/api/content/62fa1f25bacc03711136ad59',
  CONTENTDIENSTEN: '/api/content/633862b5fbcc3a3006dcda52',
  CONTENTPRIVETRAINING: '/api/trainingen/62fa1f25bacc03711136ad5f',
  ADMIN_KLANTEN_OVERVIEW: '/api/admin/klanten',
  ADMIN_KLANT_DETAIL: '/api/admin/klanten/',
  ADMIN_INSCHRIJVINGEN_OVERVIEW: '/api/admin/inschrijvingen',
  ADMIN_INSCHRIJVING_DETAIL: '/api/admin/inschrijvingen/',
  ADMIN_HONDEN_OVERVIEW: '/api/admin/honden',
  ADMIN_HOND_DETAIL: '/api/admin/honden/',
  ADMIN_RASSEN_OVERIEW: '/api/admin/rassen',
  ADMIN_RAS_DETAIL: '/api/admin/ras/',
  ADMIN_TRAINING_DAGEN: '/api/admin/trainingdays',
  FEEDBACK_API: '/api/feedback',
};

export const {
  RASSEN,
  REGISTERAPI,
  LOGINAPI,
  RESERVATIEAPI,
  KLANT_HONDEN,
  LOGOUT,
  GET_FUTURE_INSCHRIJVINGS,
  POST_INSCHRIJVING,
  TRANSFER,
  CONTACTAPI,
  CONTENTPRIVETRAINING,
  CONTENTINTRO,
  CONTENTDIENSTEN,
  ADMIN_KLANTEN_OVERVIEW,
  ADMIN_KLANT_DETAIL,
  ADMIN_INSCHRIJVINGEN_OVERVIEW,
  ADMIN_INSCHRIJVING_DETAIL,
  ADMIN_HONDEN_OVERVIEW,
  ADMIN_HOND_DETAIL,
  ADMIN_RASSEN_OVERIEW,
  ADMIN_RAS_DETAIL,
  ADMIN_TRAINING_DAGEN,
  FEEDBACK_API,
} = ApiTypes;
