const linkTypes = {
  INDEX: '/',
  HOTEL: '/hotel',
  TRAINING: '/training',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  RESERVATIE: '/reservatie',
  INSCHRIJVING: '/inschrijving',
  INSCHRIJVING_GROEP: '/inschrijving/groepslessen',
  INSCHRIJVING_PRIVE: '/inschrijving/privelessen',
  ADMIN: '/admin',
  PERSONAL: '/persoonlijke-pagina',
  ADMINEDITINDEX: '/admin/edit',
  ADMINEDITTRAININGDAYS: '/admin/edit/trainingdagen',
  ADMINLISTUSERS: '/admin/klanten',
  ADMINLISTSUBSCRIPTIONS: '/admin/inschrijvingen/',
  ADMINLISTDOGS: '/admin/honden/',
  ADMINLISTBREEDS: '/admin/rassen',
  ADMINLISTTRAININGS: '/admin/trainingen',
  ADMINEDITTRAININGTIMES: '/admin/edit/trainingtijden',
};

export const {
  INDEX,
  HOTEL,
  TRAINING,
  CONTACT,
  LOGIN,
  REGISTER,
  RESERVATIE,
  INSCHRIJVING,
  INSCHRIJVING_GROEP,
  INSCHRIJVING_PRIVE,
  ADMIN,
  PERSONAL,
  ADMINEDITINDEX,
  ADMINEDITTRAININGDAYS,
  ADMINLISTBREEDS,
  ADMINLISTDOGS,
  ADMINLISTSUBSCRIPTIONS,
  ADMINLISTTRAININGS,
  ADMINLISTUSERS,
  ADMINEDITTRAININGTIMES,
} = linkTypes;
