name: Main-Branches
on: 
  push:
    branches:
      - dev
      - accept
      - main
  pull_request:
    branches:
      - dev
      - accept
      - main

jobs:
  Base-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"

      - name: Install Packages
        run: npm i
      - name: EsLint
        run: npm run lint
      - name: Run Tests
        run: npm run test
        env:
          MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
          MONGODB_DATABASE: ${{secrets.MONGODB_DATABASE}}
