name: Run tests
on: 
  pull_request:
    branches: [main, develop, accept]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration Tests
        run: npm run test:int